---
- name: Deploy policy application Subscription
  hosts: all
  gather_facts: true
  connection: local
  tasks:   

    - name: Ensure namespace is present
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item }}"
      loop:
        - "{{ policy_namespace }}"
        - "{{ channel_namespace }}"

    - name: Create git login secret
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ channel_namespace }}-auth"
            namespace: "{{ channel_namespace }}"
          data:
            user: "{{ gitlab_token| b64encode }}"
            accessToken: "{{ gitlab_token| b64encode }}"

    - name: Create application
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: app.k8s.io/v1beta1
          kind: Application
          metadata:
            name: "{{ appname }}"
            namespace: "{{ policy_namespace }}"
          spec:
            componentKinds:
            - group: apps.open-cluster-management.io
              kind: Subscription
            descriptor: {}
            selector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - "{{ appname }}"

    - name: Create channel
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: apps.open-cluster-management.io/v1
          kind: Channel
          metadata:
            annotations:
              apps.open-cluster-management.io/reconcile-rate: high
            name: devconf-policy-apps-initiator-channel
            namespace: "{{ channel_namespace }}"
          spec:
            type: Git
            pathname: "{{ gitrepo }}"
            secretRef:
              name: "{{ channel_namespace }}-auth"

    - name: Create placement rule
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: apps.open-cluster-management.io/v1
          kind: PlacementRule
          metadata:
            labels:
              app: "{{ appname }}"
            name: "{{ appname }}-placement-1"
            namespace: "{{ policy_namespace }}"
          spec:
            clusterSelector:
              matchLabels:
                'local-cluster': 'true'

    - name: Create subscription
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig | default(omit) }}"
        validate_certs: false
        state: present
        definition:
          apiVersion: apps.open-cluster-management.io/v1
          kind: Subscription
          metadata:
            annotations:
              apps.open-cluster-management.io/git-branch: "{{ gitbranch }}"
              apps.open-cluster-management.io/git-path: "acm-policies"
              apps.open-cluster-management.io/reconcile-option: replace
            labels:
              app: "{{ appname }}"
            name: "{{ appname }}-subscription-1"
            namespace: "{{ policy_namespace }}"
          spec:
            channel: "{{ channel_namespace }}/devconf-policy-apps-initiator-channel"
            placement:
              placementRef:
                kind: PlacementRule
                name: "{{ appname }}-placement-1"
