---
apiVersion: v1
data:
  clusterid: '{{ fromClusterClaim "id.openshift.io" }} '
  clustername: '{{ fromClusterClaim "name" }}'
  ocpversion: '{{ fromClusterClaim "version.openshift.io" }}'
  platform: '{{ fromClusterClaim "platform.open-cluster-management.io" }}'
  product: '{{ fromClusterClaim "product.open-cluster-management.io" }}'
kind: ConfigMap
metadata:
  name: '{{ fromClusterClaim "name" }}'
  namespace: ztp-day2-automation


