---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cnv
  namespace: openshift-cnv
spec:
  targetNamespaces:
  - openshift-cnv
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: "stable"
  name: kubevirt-hyperconverged
  source: "redhat-operators"
  sourceNamespace: openshift-marketplace
---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  BareMetalPlatform: true
  infra:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: "node-role.kubernetes.io/master"
        operator: Exists
  workloads:
    nodePlacement:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
      - operator: Exists