#jinja2: trim_blocks: True, lstrip_blocks: True 
---
apiVersion: v1
kind: Secret
metadata:
  name: pullsecret-cluster-{{ clusterName.split('.', 1)[0] }}
  namespace: {{ clusterName.split('.', 1)[0] }} 
data:
  '.dockerconfigjson': '{{ pullSecret | to_json | b64encode }}'
type: kubernetes.io/dockerconfigjson
