apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools: 
  - name: vms
    path: "{{ secondary_storage_path | default('/var/vms') }}" 
workload:
  nodeSelector:
    kubernetes.io/os: linux
